[package]
name = "extern_attrib"
version = "0.1.0"
authors = ["anderejd <rajder@gmail.com>"]

[lib]
proc-macro = true

[dependencies.quote]
version = "0.3"

[dependencies.syn]
version = "0.11"
features = ["full", "parsing", "printing"]
